'use strict'

export default {
  animation: ['webkit'],
  animationName: ['webkit'],
  animationDuration: ['webkit'],
  animationDelay: ['webkit'],
  animationDirection: ['webkit'],
  animationFillMode: ['webkit'],
  animationIterationCount: ['webkit'],
  animationPlayState: ['webkit'],
  animationTimingFunction: ['webkit'],
  transform: ['webkit'],
  transformOrigin: ['webkit'],
  perspective: ['webkit'],
  perspectiveOrigin: ['webkit'],
  transformStyle: ['webkit'],
  backfaceVisibility: ['webkit'],
  filter: ['webkit'],
  columns: ['webkit', 'moz'],
  columnWidth: ['webkit', 'moz'],
  columnGap: ['webkit', 'moz'],
  columnRule: ['webkit', 'moz'],
  columnRuleColor: ['webkit', 'moz'],
  columnRuleWidth: ['webkit', 'moz'],
  columnCount: ['webkit', 'moz'],
  columnRuleStyle: ['webkit', 'moz'],
  columnSpan: ['webkit', 'moz'],
  columnFill: ['webkit', 'moz'],
  breakBefore: ['webkit', 'moz'],
  breakAfter: ['webkit', 'moz'],
  breakInside: ['webkit', 'moz'],
  userSelect: ['webkit', 'moz', 'ms'],
  flex: ['webkit', 'ms'],
  flexGrow: ['webkit', 'ms'],
  flexShrink: ['webkit', 'ms'],
  flexBasis: ['webkit', 'ms'],
  flexDirection: ['webkit', 'ms'],
  flexWrap: ['webkit', 'ms'],
  flexFlow: ['webkit', 'ms'],
  justifyContent: ['webkit', 'ms'],
  order: ['webkit', 'ms'],
  alignItems: ['webkit', 'ms'],
  alignSelf: ['webkit', 'ms'],
  alignContent: ['webkit', 'ms'],
  fontFeatureSettings: ['webkit'],
  fontVariantLigatures: ['webkit'],
  fontLanguageOverride: ['webkit'],
  fontKerning: ['webkit'],
  hyphens: ['webkit', 'moz', 'ms'],
  tabSize: ['moz'],
  touchAction: ['ms'],
  textDecorationStyle: ['webkit'],
  textDecorationLine: ['webkit'],
  textDecorationColor: ['webkit'],
  textSizeAdjust: ['webkit', 'ms'],
  maskClip: ['webkit'],
  maskComposite: ['webkit'],
  maskImage: ['webkit'],
  maskOrigin: ['webkit'],
  maskRepeat: ['webkit'],
  clipPath: ['webkit'],
  mask: ['webkit'],
  maskPosition: ['webkit'],
  maskSize: ['webkit'],
  boxDecorationBreak: ['webkit'],
  shapeMargin: ['webkit'],
  shapeOutside: ['webkit'],
  shapeImageThreshold: ['webkit'],
  textEmphasis: ['webkit'],
  textAlignLast: ['moz'],
  imageRendering: ['ms'],
  borderInlineStart: ['webkit', 'moz'],
  borderInlineEnd: ['webkit', 'moz'],
  marginInlineStart: ['webkit', 'moz'],
  marginInlineEnd: ['webkit', 'moz'],
  paddingInlineStart: ['webkit', 'moz'],
  paddingInlineEnd: ['webkit', 'moz'],
  borderBlockStart: ['webkit'],
  borderBlockEnd: ['webkit'],
  marginBlockStart: ['webkit'],
  marginBlockEnd: ['webkit'],
  paddingBlockStart: ['webkit'],
  paddingBlockEnd: ['webkit'],
  appearance: ['webkit', 'moz'],
}
